name: Freshdesk-Jira Sync

# Quando executar
on:
  schedule:
    - cron: '0 */2 * * *'  # A cada 2 horas
    # - cron: '0 9,14,18 * * 1-5'  # 9h, 14h, 18h (seg-sex)
  workflow_dispatch:  # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar sincronização
      env:
        # Secrets configurados no GitHub
        FRESHDESK_API_KEY: ${{ secrets.FRESHDESK_API_KEY }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
        python main.py grupo_multi --hours 2